version: '3.8'

services:
  vivek-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vivek-portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
